package com.marpak.gmpolygon.enums

enum class ButtonAction {
    CLEAR_DRAWINGS,
    START_DRAWING_SHAPE,
    STOP_DRAWING_SHAPE,
    START_DRAWING_CROSS_LINE,
    STOP_DRAWING_CROSS_LINE,
    DIVIDE_CROSS_LINE,
    START_RESIZING_SHAPE,
    STOP_RESIZING_SHAPE
}
